name: Proto Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-protos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Create output directory
      run: mkdir -p .out

    - name: Run Protoc Check
      run: |
        protoc --fatal_warnings --cpp_out=.out *.proto

    - name: Check for typos
      uses: crate-ci/typos@master
